packages:
  - apps/*
  - packages/*
  - packages/extension/*

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true

onlyBuiltDependencies:
  - core-js-bundle
  - electron
  - electron-winstaller
  - esbuild

sharedWorkspaceLockfile: false
